const fs = require('fs');

// Vercel exposes environment variables via process.env
// The user needs to add MAPILLARY_TOKEN in the Vercel project settings
const token = process.env.MAPILLARY_TOKEN || '';

if (!token) {
  console.warn('⚠️ WARNING: MAPILLARY_TOKEN environment variable is not set!');
}

const content = `// Auto-generated by vercel-build.js
window.MAPILLARY_CONFIG = {
  ACCESS_TOKEN: '${token}'
};
`;

try {
  fs.writeFileSync('config.js', content, 'utf8');
  console.log('✅ Successfully generated config.js for Vercel deployment');
} catch (error) {
  console.error('❌ Failed to write config.js:', error);
  process.exit(1);
}
